import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { UnifiedAuthButton } from "../components/UnifiedAuthButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div style={{ position: 'absolute', top: '1rem', right: '1rem' }}>
            <UnifiedAuthButton />
          </div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
